name: Marta Borkowska
title: Lucy's World
description: Snap's from the life of a little girl
remote_theme: KomunikacjaTechnicznaVistula/just-the-docs

color_scheme: vistula

logo: "/assets/images/20210829_184527.jpg"

aux_links:
  "Source repository on GitHub":
    - "//github.com/KomunikacjaTechnicznaVistula/marta-borkowska"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "This is a test page."