name: Marta Borkowska
title: Zwift - Podręcznik Użytkownika  
description: An example of technical documentation hosted on Github pages, using the Just the Docs Jekyll theme
remote_theme: KomunikacjaTechnicznaVistula/just-the-docs

color_scheme: vistula

baseurl: /Marta-Borkowska/
url: "https://komunikacjatechnicznavistula.github.io/Marta-Borkowska/"

aux_links:
  "Source repository on GitHub":
    - "//github.com/KomunikacjaTechnicznaVistula/Marta-Borkowska"

back_to_top: true
back_to_top_text: "Powrót na górę"

footer_content: "Niniejszy podręcznik powstał w ramach projektu na studiach podyplomowych Komunikacja Techniczna na Akademii Finansów i Biznesu Vistula. Stan wszelkich informacji i zrzutów ekranu na dzień 14.02.2022 r."