name: Marta Borkowska
title: Zwift - krótki podręcznik Użytkownika
description: An example of technical documentation hosted on Github pages, using the Just the Docs Jekyll theme
remote_theme: KomunikacjaTechnicznaVistula/just-the-docs

color_scheme: vistula

logo: "assets/images/"

aux_links:
  "Source repository on GitHub":
    - "//github.com/KomunikacjaTechnicznaVistula/marta-borkowska"

back_to_top: true
back_to_top_text: "Powrót na górę"

footer_content: "Niniejszy podręcznik powstał w ramach projektu na studiach podyplomowych Komunikacja Techniczna na Akademii Finansów i Biznesu Vistula. Stan wszelkich informacji i zrzutów ekranu na dzień 14.02.2022 r."